language: rust
rust: nightly
jobs:
    include:
      - os: linux
        before_install:
          - apt update
          - apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl 
        before_script:
          - rustup target add wasm32-unknown-unknown --toolchain nightly
        script:
          - export RUST_BACKTRACE=1 && cargo build --verbose
          - export RUST_BACKTRACE=1 && cargo test --verbose
          - export RUST_BACKTRACE=1 && cargo doc --no-deps --verbose
      - os: windows
        before_install:
          - apt update
          - apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl 
        before_script:
          - rustup target add wasm32-unknown-unknown --toolchain nightly
        script:
          - export RUST_BACKTRACE=1 && cargo build --verbose
          - export RUST_BACKTRACE=1 && cargo test --verbose
          - export RUST_BACKTRACE=1 && cargo doc --no-deps --verbose
      - os: osx
        before_install:
          - apt update
          - apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl 
        before_script:
          - rustup target add wasm32-unknown-unknown --toolchain nightly
        script:
          - export RUST_BACKTRACE=1 && cargo build --verbose
          - export RUST_BACKTRACE=1 && cargo test --verbose
          - export RUST_BACKTRACE=1 && cargo doc --no-deps --verbose
      # - fast_finish: true
      # Coverage build only on master and PRs
      - if: branch = master # require the branch name to be master (note for PRs this is the base branch name)
        name: Coverage
        before_install:
          - apt update
          - apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl 
          - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
        before_script:
          - rustup component add llvm-tools-preview
          - rustup target add wasm32-unknown-unknown --toolchain nightly
        script:
          - export CARGO_INCREMENTAL=0 &&
            export RUSTFLAGS="-Zinstrument-coverage" &&
            export LLVM_PROFILE_FILE="mantanode-%p-%m.profraw" &&
            export RUSTDOCFLAGS="-Cpanic=abort" &&
            cargo test --verbose
          - ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info # from https://crates.io/crates/grcov/0.5.13#grcov-with-travis
          - bash <(curl -s https://codecov.io/bash) -f lcov.info